// /*
// * This Java source file was generated by the Gradle 'init' task.
// */
// package bitcamp.myapp;

// // 코드 본문에서 사용할 클래수가 어떤 패키지의 클래스인지 지정한다.
// import java.io.InputStream;
// import java.util.Scanner;

// public class App {
// public static void main(String[] args) {
// System.out.println("나의 목록 관리 시스템");
// System.out.println("---------------------------------");

// // 키보드 스캐너 준비
// InputStream keyboard = System.in;
// Scanner scanner = new Scanner(System.in);

// int[] no1 = new int[3];
// String[] name1 = new String[3];
// int[] age1 = new int[3];
// boolean[] working1 = new boolean[3];
// char[] gender1 = new char[3];
// float[] lefteye1 = new float[3];
// float[] righteye1 = new float[3];

// for (int count = 0; count < 3; count++) {
// // count++;
// // count = count +1;
// // count += 1;

// System.out.print("번호? ");

// no1[count] = scanner.nextInt();

// System.out.print("이름? ");
// name1[count] = scanner.next();

// System.out.print("나이? ");

// age1[count] = scanner.nextInt();

// System.out.print("재직중(true/false)? ");

// working1[count] = scanner.nextBoolean();

// System.out.print("성별(남자:M , 여자:W) ? ");
// String str = scanner.next();
// gender1[count] = str.charAt(0);

// System.out.print("시력(왼쪽,오른쪽) ?");
// lefteye1[count] = scanner.nextFloat();
// righteye1[count] = scanner.nextFloat();

// }
// for (int count = 0; count < 3; count++) {

// System.out.println("----------------------------");

// System.out.printf("번호: %d\n", no1[count]);
// System.out.printf("이름 : %s\n", name1[count]);
// System.out.printf("나이 : %d\n", age1[count]);
// System.out.printf("재직자 : %b\n", working1[count]);
// System.out.printf("성별(남자(M), 여자(W)): %c\n", gender1[count]);
// System.out.printf("좌우시력: %f,%f\n", lefteye1[count], righteye1[count]);

// scanner.close();
// }
// }

// }
